--------------------------------------------------------
--  
--------------------------------------------------------
DROP TABLE IF EXISTS HYDRA_TRAINER;
CREATE TABLE HYDRA_TRAINER(
	TRAINER_ID INT(10) PRIMARY KEY,
	EMAIL VARCHAR(30) UNIQUE NOT NULL,
	NAME VARCHAR(30),
	TITLE VARCHAR(30),
	TIER VARCHAR(30),
	RESUME VARCHAR(30)
);

DROP TABLE IF EXISTS HYDRA_CERTIFICATION;
CREATE TABLE HYDRA_CERTIFICATION(
	CERT_ID int(10) PRIMARY KEY,
	URL VARCHAR(200),
	NAME VARCHAR(30),
	TRAINER INT(10)
);
--------------------------------------------------------
--  DDL for Sequence TRAINER_ID_SEQUENCE
--------------------------------------------------------
DROP SEQUENCE IF EXISTS TRAINER_ID_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS TRAINER_ID_SEQUENCE MINVALUE 1 INCREMENT BY 1 START WITH 1;
DROP SEQUENCE IF EXISTS CERT_ID_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS CERT_ID_SEQUENCE MINVALUE 1 INCREMENT BY 1 START WITH 1;


INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'patrick.walsh@revature.com', 'Patrick Walsh', 'Lead Trainer', 'ROLE_VP', 'resume1');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'pjw6193@hotmail.com', 'Dan Pickles', 'Lead Trainer', 'ROLE_VP', 'resume2');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'ravi.singh@revature.com', 'Ravi Singh', 'Vice President of Technology', 'ROLE_VP', 'resume3');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'karan.dhirar@revature.com', 'Karan Dhirar', 'Technology Manager', 'ROLE_VP', 'resume4');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'brian.connolly@revature.com', 'Brian Connolly', 'Senior Java Developer', 'ROLE_VP', 'resume5');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'genesis.bonds@revature.com', 'Genesis Bonds', 'Trainer', 'ROLE_TRAINER', 'resume6');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'ankit.garg@revature.com', 'Ankit Garg', 'Lead Trainer', 'ROLE_TRAINER', 'resume7');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'ryan.lessley@revature.com', 'Ryan Lessley', 'Senior Trainer', 'ROLE_TRAINER', 'resume8');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'steven.kelsey@revature.com', 'Steven Kelsey', 'Senior Trainer', 'ROLE_TRAINER', 'resume9');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'emily.higgins@revature.com', 'Emily Higgins', 'Trainer', 'ROLE_TRAINER', 'resume10');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'taylor.kemper@revature.com', 'Taylor Kemper', 'Senior Trainer', 'ROLE_TRAINER', 'resume11');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'richard.orr@revature.com', 'Richard Orr', 'Trainer', 'ROLE_TRAINER', 'resume12');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'nickolas.jurczak@revature.com', 'Nickolas Jurczak', 'Trainer', 'ROLE_TRAINER', 'resume13');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'august.duet@revature.com', 'August Duet', 'Trainer', 'ROLE_TRAINER', 'resume14');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'yuvarajd@revature.com', 'Yuvaraj Damodaran', 'Lead Trainer', 'ROLE_TRAINER', 'resume15');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'fred.belotte@revature.com', 'Fred Belotte', 'Senior Trainer', 'ROLE_TRAINER', 'resume16');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'mehrab.rahman@revature.com', 'Mehrab Rahman', 'Trainer', 'ROLE_TRAINER', 'resume17');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'peter.alagna@revature.com', 'Peter Alagna', 'Trainer', 'ROLE_TRAINER', 'resume18');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'stanleym@revature.com', 'Stanley Medikonda', 'Staging Manager', 'ROLE_STAGING', 'resume19');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'grawyne@gmail.com', 'Gray Wynne', 'Trainer', 'ROLE_TRAINER', 'resume20');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'owallace@mailinator.com', 'Orson Wallace', 'Trainer', 'ROLE_TRAINER', 'resume21');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'slevinson@mailinator.com', 'Shelby Levinson', 'Trainer', 'ROLE_TRAINER', 'resume22');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'wpayne@mailinator.com', 'Walter Payne', 'Trainer', 'ROLE_TRAINER', 'resume23');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'nchurch@mailinator.com', 'Natalie Church', 'Trainer', 'ROLE_TRAINER', 'resume24');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'aradcliff@mailinator.com', 'Archer Radcliff', 'Trainer', 'ROLE_TRAINER', 'resume25');
--------------------------------------------------------------------------------------------------------------------MAKE PANEL ROLE
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'rajeshy@revature.com', 'Rajesh Yamunachari', 'Senior Technical Manager', 'ROLE_PANEL', 'resume26');
INSERT INTO HYDRA_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER, RESUME) VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'raghavan@revature.com', 'Raghavan Swaminathan', 'Senior Technical Manager', 'ROLE_PANEL', 'resume27');
-------------TRAINER END-------------

INSERT INTO HYDRA_CERTIFICATION(CERT_ID, URL, NAME, TRAINER) VALUES (CERT_ID_SEQUENCE.NEXTVAL, 'URL1', 'CERT1', 1);
INSERT INTO HYDRA_CERTIFICATION(CERT_ID, URL, NAME, TRAINER) VALUES (CERT_ID_SEQUENCE.NEXTVAL, 'URL1', 'CERT1', 20);
INSERT INTO HYDRA_CERTIFICATION(CERT_ID, URL, NAME, TRAINER) VALUES (CERT_ID_SEQUENCE.NEXTVAL, 'URL1', 'CERT1', 15);
INSERT INTO HYDRA_CERTIFICATION(CERT_ID, URL, NAME, TRAINER) VALUES (CERT_ID_SEQUENCE.NEXTVAL, 'URL2', 'CERT2', 1);
COMMIT;